#include <stdio.h>

typedef enum
{
  PT_HINT_NONE = 0,
  PT_HINT_ORDERED = 1ULL << 0,
  PT_HINT_NO_INDEX_SS = 1ULL << 1,
  PT_HINT_INDEX_SS = 1ULL << 2,
  PT_HINT_SELECT_BTREE_NODE_INFO = 1ULL << 3,
  PT_HINT_USE_NL = 1ULL << 4,
  PT_HINT_USE_IDX = 1ULL << 5,
  PT_HINT_USE_MERGE = 1ULL << 6,
  PT_HINT_USE_HASH = 1ULL << 7,
  PT_HINT_RECOMPILE = 1ULL << 8,
  PT_HINT_LK_TIMEOUT = 1ULL << 9,
  PT_HINT_NO_LOGGING = 1ULL << 10,
  PT_HINT_NO_HASH_LIST_SCAN = 1ULL << 11,
  PT_HINT_QUERY_CACHE = 1ULL << 12,
  PT_HINT_REEXECUTE = 1ULL << 13,
  PT_HINT_JDBC_CACHE = 1ULL << 14,
  PT_HINT_USE_SBR = 1ULL << 15,
  PT_HINT_USE_IDX_DESC = 1ULL << 16,
  PT_HINT_NO_COVERING_IDX = 1ULL << 17,
  PT_HINT_INSERT_MODE = 1ULL << 18,
  PT_HINT_NO_IDX_DESC = 1ULL << 19,
  PT_HINT_NO_MULTI_RANGE_OPT = 1ULL << 20,
  PT_HINT_USE_UPDATE_IDX = 1ULL << 21,
  PT_HINT_USE_INSERT_IDX = 1ULL << 22,
  PT_HINT_NO_SORT_LIMIT = 1ULL << 23,
  PT_HINT_NO_HASH_AGGREGATE = 1ULL << 24,
  PT_HINT_SKIP_UPDATE_NULL = 1ULL << 25,
  PT_HINT_NO_INDEX_LS = 1ULL << 26,
  PT_HINT_INDEX_LS = 1ULL << 27,
  PT_HINT_NO_SUPPLEMENTAL_LOG = 1ULL << 28,
  PT_HINT_SELECT_RECORD_INFO = 1ULL << 29,
  PT_HINT_SELECT_PAGE_INFO = 1ULL << 30,
  PT_HINT_SELECT_KEY_INFO = 1ULL << 31,
  PT_HINT_QUERY_NO_CACHE = 1ULL << 32,
  PT_HINT_NO_PUSH_PRED = 1ULL << 33,
  PT_HINT_NO_MERGE = 1ULL << 34,
  PT_HINT_NO_ELIMINATE_JOIN = 1ULL << 35,
  PT_HINT_LAST = PT_HINT_NO_ELIMINATE_JOIN,
} PT_HINT_ENUM;

typedef struct parser_node PT_NODE;
struct parser_node
{
  PT_HINT_ENUM hint;
};

void
pt_set_hint_to_select (PT_NODE * const node, PT_HINT_ENUM hint)
{
  node->hint |= hint;
}

void main()
{
  PT_NODE node;
  node.hint = PT_HINT_NONE;
  pt_set_hint_to_select (&node, PT_HINT_NO_ELIMINATE_JOIN);
  pt_set_hint_to_select (&node, PT_HINT_NO_ELIMINATE_JOIN | PT_HINT_NO_MERGE);  



}
