CREATE TRIGGER [prj_pjct_ai01_tg] BEFORE INSERT ON prj_A EXECUTE 
AFTER 
  INSERT INTO [prj_A_hist] (
    [pjct_manage_no], [valid_begin_dt], 
    [valid_end_dt], [pjct_nm], [pjct_manage_step_code], 
    [pjct_progrs_sttus_code], [bsn_progrs_sttus_code], 
    [bid_propse_progrs_sttus_code], 
    [pjct_flfl_sttus_code], [opbid_progrs_sttus_code], 
    [slscg_cnstn_mnno], [bsn_reprs_appn_at], 
    [bstgt_cstmr_prscg_idntfc_at], 
    [bsn_cmptr_info_idntfc_at], [bsn_corpt_info_idntfc_at], 
    [dmand_instt_code], [dmand_instt_nm], 
    [intbs_excl_at], [propse_parpt_at], 
    [propse_prsnt_ennc], [online_prsnt_at], 
    [intbs_at], [bid_cndcy_at], [bdng_at], 
    [rcvord_at], [evl_mby_code], [quntv_evl_mth_code], 
    [bsn_grad_code], [bid_parpt_cnd_code], 
    [intbs_exarq_dt], [techl_evl_dt], 
    [intbs_appn_dt], [intbs_excl_dt], 
    [bidpt_confm_dt], [bdng_dt], [intbs_exarq_cnstn_mnno], 
    [intbs_exmnt_cnstn_mnno], [intbs_excl_cnstn_mnno], 
    [bidpt_confm_cnstn_mnno], [prpcg_cnstn_mnno], 
    [exccg_cnstn_mnno], [intbs_chckr_chgrq_cn], 
    [prftbl_cn], [parpt_resn_cn], [qltve_dc_cn], 
    [sumry_dcmnt_cn], [qltve_evl_at], 
    [prsdt_writng_at], [prntng_ennc], 
    [beffat_bsn_succes_at], [inpt_hnf_dcsn_at], 
    [prsmp_prc], [nbsh_cnvrsn_untpc_amt], 
    [work_stdr_time_code], [bsns_begin_de], 
    [bsns_end_de], [bsn_oder_expect_ym], 
    [ceo_ipcr_at], [budget_cyfd_at], 
    [change_resn_cn], [frst_crtr_id], 
    [frcrt_dt], [last_updusr_id], [lsupd_dt], 
    [stdr_de]
  ) 
VALUES 
  (
    [obj].[pjct_manage_no], 
    TO_CHAR(
      SYS_DATETIME, 'YYYYMMDDHH24MISS'
    ), 
    '99991231' || '235959', 
    [obj].[pjct_nm], 
    [obj].[pjct_manage_step_code], 
    [obj].[pjct_progrs_sttus_code], 
    [obj].[bsn_progrs_sttus_code], 
    [obj].[bid_propse_progrs_sttus_code], 
    [obj].[pjct_flfl_sttus_code], 
    [obj].[opbid_progrs_sttus_code], 
    [obj].[slscg_cnstn_mnno], 
    [obj].[bsn_reprs_appn_at], 
    [obj].[bstgt_cstmr_prscg_idntfc_at], 
    [obj].[bsn_cmptr_info_idntfc_at], 
    [obj].[bsn_corpt_info_idntfc_at], 
    [obj].[dmand_instt_code], 
    [obj].[dmand_instt_nm], 
    [obj].[intbs_excl_at], 
    [obj].[propse_parpt_at], 
    [obj].[propse_prsnt_ennc], 
    [obj].[online_prsnt_at], 
    [obj].[intbs_at], 
    [obj].[bid_cndcy_at], 
    [obj].[bdng_at], 
    [obj].[rcvord_at], 
    [obj].[evl_mby_code], 
    [obj].[quntv_evl_mth_code], 
    [obj].[bsn_grad_code], 
    [obj].[bid_parpt_cnd_code], 
    [obj].[intbs_exarq_dt], 
    [obj].[techl_evl_dt], 
    [obj].[intbs_appn_dt], 
    [obj].[intbs_excl_dt], 
    [obj].[bidpt_confm_dt], 
    [obj].[bdng_dt], 
    [obj].[intbs_exarq_cnstn_mnno], 
    [obj].[intbs_exmnt_cnstn_mnno], 
    [obj].[intbs_excl_cnstn_mnno], 
    [obj].[bidpt_confm_cnstn_mnno], 
    [obj].[prpcg_cnstn_mnno], 
    [obj].[exccg_cnstn_mnno], 
    [obj].[intbs_chckr_chgrq_cn], 
    [obj].[prftbl_cn], 
    [obj].[parpt_resn_cn], 
    [obj].[qltve_dc_cn], 
    [obj].[sumry_dcmnt_cn], 
    [obj].[qltve_evl_at], 
    [obj].[prsdt_writng_at], 
    [obj].[prntng_ennc], 
    [obj].[beffat_bsn_succes_at], 
    [obj].[inpt_hnf_dcsn_at], 
    [obj].[prsmp_prc], 
    [obj].[nbsh_cnvrsn_untpc_amt], 
    [obj].[work_stdr_time_code], 
    [obj].[bsns_begin_de], 
    [obj].[bsns_end_de], 
    [obj].[bsn_oder_expect_ym], 
    [obj].[ceo_ipcr_at], 
    [obj].[budget_cyfd_at], 
    [obj].[change_resn_cn], 
    [obj].[frst_crtr_id], 
    [obj].[frcrt_dt], 
    [obj].[last_updusr_id], 
    [obj].[lsupd_dt], 
    [obj].[stdr_de]
  );

ALTER TRIGGER prj_pjct_ai01_tg STATUS ACTIVE;
