/* DO NOT EDIT THIS FILE - it is machine generated */
#include "JNIExample.h"

#include <dlfcn.h>
#include <jni.h>
#include <stdio.h>
#include <string.h>

#include "dbi.h"
/* Header for class JNIExample */




enum er_exit_ask
{
  ER_NEVER_EXIT = 0,
  ER_EXIT_ASK = 1,
  ER_EXIT_DONT_ASK = 2,
  ER_ABORT = 3,
  ER_EXIT_DEFAULT = ER_NEVER_EXIT
};

enum intl_codeset
{
  INTL_CODESET_ERROR = -2,
  INTL_CODESET_NONE = -1,
  INTL_CODESET_ASCII,		/* US English charset, ASCII encoding */
  INTL_CODESET_RAW_BITS,	/* Uninterpreted bits, Raw encoding */
  INTL_CODESET_RAW_BYTES,	/* Uninterpreted bytes, Raw encoding */
  INTL_CODESET_ISO88591,	/* Latin 1 charset, ISO 8859 encoding */
  INTL_CODESET_KSC5601_EUC,	/* KSC 5601 1990 charset , EUC encoding */
  INTL_CODESET_UTF8,		/* UNICODE charset, UTF-8 encoding */

  INTL_CODESET_BINARY = INTL_CODESET_RAW_BYTES,

  INTL_CODESET_LAST = INTL_CODESET_UTF8
};
typedef enum intl_codeset INTL_CODESET;

/* GLOBAL STATE */
#define DB_CONNECTION_STATUS_NOT_CONNECTED	0
#define DB_CONNECTION_STATUS_CONNECTED		1
#define DB_CONNECTION_STATUS_RESET		-1




/*
 * Class:     JNIExample
 * Method:    db_open_buffer_local
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIExample_hello
  (JNIEnv *env, jobject jObj, jstring jStr)
{
  void *dl_handle = NULL;
  char * version = NULL;
  const char *buf = NULL;
  char *query = NULL;
  DB_SESSION *session = NULL;
  DB_SESSION_ERROR *errs;
  int error = 0;

  int (*cub_er_init) (const char *msglog_filename, int exit_ask);
  int (*cub_er_errid) ();
  const char * (*cub_er_msg) ();
  DB_SESSION_ERROR * (*cub_db_get_errors) (DB_SESSION * session);
  DB_SESSION_ERROR * (*cub_db_get_next_error) (DB_SESSION_ERROR * errors, int *line, int *col);
  char * (*cub_db_get_database_version) ();
  int (*cub_lang_init) ();	/* lang_Initialized */
  int (*cub_lang_set_charset_lang) (const char *lang_charset);	/* lang_Language_initialized */
  void (*cub_db_set_connect_status) (int status);
  DB_SESSION * (*cub_db_open_buffer) (char * query);

  dl_handle = dlopen ("/home/youngjinj/CUBRID/lib/libcubridcs.so", RTLD_LAZY);
  if (dl_handle == NULL)
    {
      printf ("[ERROR] dlopen.\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_er_init = (int (*)(const char *, int)) dlsym (dl_handle, "er_init");
  if (cub_er_init == NULL)
    {
      printf ("[ERROR] dlsym - er_init().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  error = cub_er_init (NULL, ER_NEVER_EXIT);
  if (error != 0)
    {
      printf ("[ERROR] er_init() (%d).\n", error);
      return;
    }

  cub_er_errid = (int (*)()) dlsym (dl_handle, "er_errid");
  if (cub_er_errid == NULL)
    {
      printf ("[ERROR] dlsym - er_errid().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_er_msg = (const char * (*)()) dlsym (dl_handle, "er_msg");
  if (cub_er_msg == NULL)
    {
      printf ("[ERROR] dlsym - er_msg().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_db_get_errors = (DB_SESSION_ERROR * (*)(DB_SESSION *)) dlsym (dl_handle, "db_get_errors");
  if (cub_db_get_errors == NULL)
    {
      printf ("[ERROR] dlsym - db_get_errors().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_db_get_next_error = (DB_SESSION_ERROR * (*)(DB_SESSION_ERROR *, int *, int *)) dlsym (dl_handle, "db_get_next_error");
  if (cub_db_get_next_error == NULL)
    {
      printf ("[ERROR] dlsym - db_get_next_error().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_db_get_database_version = (char * (*)()) dlsym (dl_handle, "db_get_database_version");
  if (cub_db_get_database_version == NULL)
    {
      printf ("[ERROR] dlsym - db_get_database_version().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  version = cub_db_get_database_version ();
  printf ("Version: %s\n", version);

  cub_lang_init = (int (*)()) dlsym (dl_handle, "lang_init");
  if (cub_lang_init == NULL)
    {
      printf ("[ERROR] dlsym - lang_init().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_lang_init ();

  cub_lang_set_charset_lang = (int (*)(const char *)) dlsym (dl_handle, "lang_set_charset_lang");
  if (cub_lang_set_charset_lang == NULL)
    {
      printf ("[ERROR] dlsym - lang_set_charset_lang().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_lang_set_charset_lang ("ko_KR.utf8");

  cub_db_set_connect_status = (void (*)(int)) dlsym (dl_handle, "_Z21db_set_connect_statusi");
  if (cub_db_set_connect_status == NULL)
    {
      printf ("[ERROR] dlsym - db_set_connect_status().\n");
      printf ("\t%s\n", dlerror ());
      return;
    }

  cub_db_set_connect_status (DB_CONNECTION_STATUS_CONNECTED);

  buf = (*env)->GetStringUTFChars (env, jStr, NULL);
  query = strdup (buf);
  (*env)->ReleaseStringUTFChars(env, jStr, buf);
  printf("Query: %s\n", query);

  /* nm $CUBRID/lib/libcubridcs.so | grep db_open_buffer | awk '{print $NF}' */
  cub_db_open_buffer = (DB_SESSION * (*)(char *)) dlsym (dl_handle, "db_open_buffer");
  if (cub_db_open_buffer == NULL)
    {
      printf ("[ERROR] dlsym - db_open_buffer().\n");
      printf ("\t%s\n", dlerror ());
      free (query);
      return;
    }

  session = cub_db_open_buffer (query);
  errs = cub_db_get_errors (session);
  do
    {
      int line, col;

      errs = cub_db_get_next_error (errs, &line, &col);

      error = cub_er_errid ();
      if (error != 0)
	{
	  printf ("[RESULT] error: %d\n", error);
	  printf ("\t%s\n", cub_er_msg ());
	}
    }
  while (errs);

  free (query);

  error = dlclose (dl_handle);
  if ( error != 0 )
    {
      printf ("[ERROR] dlclose.\n");
      printf ("\t%s\n", dlerror ());
    }
/*
jstring javaString = env->NewStringUTF(nativeString);
// use your string
env->DeleteLocalRef(javaString);
*/
  return;
}

/* https://stackoverflow.com/questions/41820039/jstringjni-to-stdstringc-with-utf8-characters *
string jstring2string(JNIEnv *env, jstring jStr)
{
  if (jStr == NULL)
    {
      return "";
    }

  const jclass stringClass = env->GetObjectClass(jStr);
  const jmethodID getBytes = env->GetMethodID(stringClass, "getBytes", "(Ljava/lang/String;)[B");
  const jbyteArray stringJbytes = (jbyteArray) env->CallObjectMethod(jStr, getBytes, env->NewStringUTF("UTF-8"));

  size_t length = (size_t) env->GetArrayLength(stringJbytes);
  jbyte* pBytes = env->GetByteArrayElements(stringJbytes, NULL);

  std::string ret = std::string((char *)pBytes, length);
    env->ReleaseByteArrayElements(stringJbytes, pBytes, JNI_ABORT);

    env->DeleteLocalRef(stringJbytes);
    env->DeleteLocalRef(stringClass);
    return ret;
}
/**/