csql -u dba  demodb -S -i create.sql >  dba.out
csql -u u0   demodb -S -i result.sql >   u0.out
csql -u u1   demodb -S -i result.sql >   u1.out
csql -u u1_1 demodb -S -i result.sql > u1_1.out
csql -u u2   demodb -S -i result.sql >   u2.out
csql -u u2_1 demodb -S -i result.sql > u2_1.out
csql -u u3   demodb -S -i result.sql >   u3.out
csql -u u3_1 demodb -S -i result.sql > u3_1.out
csql -u u4   demodb -S -i result.sql >   u4.out
csql -u u5   demodb -S -i result.sql >   u5.out
csql -u u6   demodb -S -i result.sql >   u6.out
