csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
csql_C_demodb -i insert.sql
